
version: "3.5"

networks:
  elknet:
    driver: bridge
    internal: true
    external: false
    attachable: true

services:


  kib01:
    image: docker.elastic.co/kibana/kibana:7.4.2
    #container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks: [ elknet ]

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    #container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: []
    ports:
      - 9201:9200
    networks: [ elknet ]

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    #container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: []
    ports:
      - 9202:9200
    networks: [ elknet ]

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    #container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: []
    ports:
      - 9203:9200
    networks: [ elknet ]
